CREATE TABLE `calculator_leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(30) NOT NULL,
	`age` int NOT NULL,
	`weight` int NOT NULL,
	`height` int NOT NULL,
	`tdee` int NOT NULL,
	`bmr` int NOT NULL,
	`protein` int NOT NULL,
	`carbs` int NOT NULL,
	`fats` int NOT NULL,
	`smsStatus` varchar(20) NOT NULL DEFAULT 'pending',
	`sms1SentAt` timestamp,
	`sms2SentAt` timestamp,
	`sms3SentAt` timestamp,
	`sms1MessageId` varchar(100),
	`sms2MessageId` varchar(100),
	`sms3MessageId` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `calculator_leads_id` PRIMARY KEY(`id`)
);
